name: Hello world
  on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
    workflow_dispatch:

jobs:
# name of the job
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello 
        run: echo "Hello World bro"
        shell: bash
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Good bye world
        run: echo "Good Bye World"
        shell: bash      